"""Turn the validation JSON records into the appendix table `checks_table.tex`.

    python paper/make_checks_table.py        (after scripts/validation/run_all.py)

One row per check: id/name, criterion (the `expect` field, trimmed at the first
sentence), the measured result (trimmed), and the outcome (pass / known / fail).
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "_results/validation"
OUT = ROOT / "paper/checks_table.tex"
TIERS = [("A", "Tier A — cylinder: first principles, analytical, FEM, pipeline"),
         ("B", "Tier B — MUAP features against the literature"),
         ("C", "Tier C — interference EMG and motor-unit pool"),
         ("S", "Tier S — chain-level sanity")]


def tex(s: str) -> str:
    s = (s.replace("\\", "\\textbackslash{}").replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
          .replace("#", "\\#").replace("{", "\\{").replace("}", "\\}").replace("~", "$\\sim$").replace("^", "\\^{}"))
    for a, b in {"≥": "$\\geq$", "≤": "$\\leq$", "≈": "$\\approx$", "→": "$\\to$", "×": "$\\times$", "µ": "$\\mu$",
                 "φ": "$\\varphi$", "σ": "$\\sigma$", "Δ": "$\\Delta$", "ρ": "$\\rho$", "θ": "$\\theta$",
                 "∫": "$\\int$", "√": "$\\surd$", "″": "$''$", "′": "$'$", "−": "$-$", "±": "$\\pm$", "·": "$\\cdot$",
                 "Σ": "$\\Sigma$", "≡": "$\\equiv$", "∝": "$\\propto$", "Ø": "$\\varnothing$", "α": "$\\alpha$",
                 "½": "1/2", "…": "\\ldots{}", "—": "---", "–": "--", "✓": "", "⇒": "$\\Rightarrow$", "∀": "$\\forall$",
                 "²": "$^2$", "³": "$^3$", "⁻": "$^-$", "⁶": "$^6$", "¹": "$^1$", "⁷": "$^7$", "°": "$^\\circ$",
                 "λ": "$\\lambda$", "π": "$\\pi$", "ξ": "$\\xi$"}.items():
        s = s.replace(a, b)
    return s


def clip(s: str, n: int) -> str:
    """Escape, then cut at a word boundary near n characters (ellipsis added after escaping)."""
    s = tex(s.strip())
    return s if len(s) <= n else s[:n].rsplit(" ", 1)[0] + "\\ldots{}"


rows = []
for tier, title in TIERS:
    recs = [r for r in json.loads((SRC / f"{tier}.json").read_text()) if r["tier"] == tier]
    rows.append(f"\\midrule\n\\multicolumn{{4}}{{l}}{{\\textit{{{tex(title)}}}}} \\\\\n\\midrule")
    for r in recs:
        outcome = "pass" if r["passed"] else ("known" if r["known"] else "\\textbf{fail}")
        name = clip(r["name"], 110)
        exp = clip(r["expect"], 150)
        meas = clip(r["measured"], 160)
        rows.append(f"{name} & {exp} & {meas} & {outcome} \\\\")
table = "\n".join(rows)
OUT.write_text(
    "% generated by paper/make_checks_table.py — do not edit\n"
    "\\begin{longtable}{p{41mm}p{44mm}p{47mm}p{9mm}}\n"
    "\\caption{Every check of the validation suite: what it asserts, its criterion (first clause), what was "
    "measured (first clause), and the outcome. Full strings are in \\texttt{docs/validation/REPORT.md}.}\\label{tab:checks}\\\\\n"
    "\\toprule check & criterion & measured & result \\\\\n\\endfirsthead\n"
    "\\toprule check & criterion & measured & result \\\\\n\\endhead\n"
    + table + "\n\\bottomrule\n\\end{longtable}\n")
print("wrote", OUT, "rows:", sum(1 for r in rows if r.endswith("\\\\") and "multicolumn" not in r))
